version: '3.4'
services:
  monero.dnp.dappnode.eth:
    build: ./build
    image: 'monero.dnp.dappnode.eth:0.2.4'
    ports:
      - '18080:18080'
      - '18081:18081'
    volumes:
      - 'data:/root/.bitmonero'
    environment:
      - EXTRA_FLAGS=
volumes:
  data: {}
